


export const CONFIRM_FILTER_PERSONEL = 'CONFIRM_FILTER_PERSONEL'
export const CONFIRM_SORT_PERSONEL = 'CONFIRM_SORT_PERSONEL'

export const TWO_FACTOR_CONFIRM_CODE_DONE = 'TWO_FACTOR_CONFIRM_CODE_DONE'

export const LOGOUT_COMMAND = 'LOGOUT_COMMAND'
export const CONFIRM_LOGOUT_COMMAND = 'CONFIRM_LOGOUT_COMMAND'

export const CONFIRM_NEW_USER_CREATED = 'CONFIRM_NEW_USER_CREATED'

export const DELETE_PERMISSION_COMMAND = 'DELETE_PERMISSION_COMMAND'
export const CONFIRM_DELETE_PERMISSION = 'CONFIRM_DELETE_PERMISSION'

export const DELETE_USER_ROLE_COMMAND = 'DELETE_USER_ROLE_COMMAND'
export const CONFIRM_DELETE_USER_ROLE = 'CONFIRM_DELETE_USER_ROLE'
